services:
  - type: web
    name: eventpro-api
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: APP_URL
        fromService:
          type: web
          name: eventpro-api
          property: host
      - key: BREVO_API_KEY
        sync: false
      - key: DARAJA_ENV
        value: sandbox
      - key: DARAJA_CONSUMER_KEY
        sync: false
      - key: DARAJA_CONSUMER_SECRET
        sync: false
      - key: DARAJA_PASSKEY
        sync: false
      - key: DARAJA_SHORTCODE
        value: "174379"
      - key: DARAJA_CALLBACK_URL
        sync: false
      - key: PAYSTACK_SECRET_KEY
        sync: false
      - key: PAYSTACK_PUBLIC_KEY
        sync: false
