// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpi3Mi2dS3Oh1wTKnwaUYAkYV3J77xWIU',
    appId: '1:472380070338:android:684129b7c712c69ea8de5b',
    messagingSenderId: '472380070338',
    projectId: 'eventproagency-aec59',
    storageBucket: 'eventproagency-aec59.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlEYuc2DHedrJ6aMGU5WhydIZYeX32aNI',
    appId: '1:472380070338:ios:a7c9211f64e5bd20a8de5b',
    messagingSenderId: '472380070338',
    projectId: 'eventproagency-aec59',
    storageBucket: 'eventproagency-aec59.firebasestorage.app',
    iosBundleId: 'com.eventpro.eventproagency',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKF_KzfhwtoeMwupbhJAUtGtpex4kcS5k',
    appId: '1:472380070338:web:d1912d585ef13030a8de5b',
    messagingSenderId: '472380070338',
    projectId: 'eventproagency-aec59',
    authDomain: 'eventproagency-aec59.firebaseapp.com',
    storageBucket: 'eventproagency-aec59.firebasestorage.app',
    measurementId: 'G-34J7KH2K4F',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlEYuc2DHedrJ6aMGU5WhydIZYeX32aNI',
    appId: '1:472380070338:ios:a7c9211f64e5bd20a8de5b',
    messagingSenderId: '472380070338',
    projectId: 'eventproagency-aec59',
    storageBucket: 'eventproagency-aec59.firebasestorage.app',
    iosBundleId: 'com.eventpro.eventproagency',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKF_KzfhwtoeMwupbhJAUtGtpex4kcS5k',
    appId: '1:472380070338:web:14bd7d25198e2a3ba8de5b',
    messagingSenderId: '472380070338',
    projectId: 'eventproagency-aec59',
    authDomain: 'eventproagency-aec59.firebaseapp.com',
    storageBucket: 'eventproagency-aec59.firebasestorage.app',
    measurementId: 'G-FGQ3CGX847',
  );
}
